name: "gn auto update"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  get_current_info:
    runs-on: ubuntu-latest
    outputs:
      pkg_source_version: ${{ steps.info.outputs.pkg_source_version }}
      pkg_source_date: ${{ steps.info.outputs.pkg_source_date }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: info
        id: info
        run: |
          echo "pkg_source_version=$(grep 'PKG_SOURCE_VERSION:=' gn/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
          echo "pkg_source_date=$(grep 'PKG_SOURCE_DATE:=' gn/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT

  get_latest_info:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.info.outputs.commit_sha }}
      commit_date: ${{ steps.info.outputs.commit_date }}
      short_ver: ${{ steps.info.outputs.short_ver }}
      long_ver: ${{ steps.info.outputs.long_ver }}
      commit_position: ${{ steps.info.outputs.commit_position }}
      checksum: ${{ steps.info.outputs.checksum }}
    steps:
      - name: clone gn
        run: git clone https://gn.googlesource.com/gn.git gn-src

      - name: info
        id: info
        run: |
          echo "commit_sha=$(git -C gn-src rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "commit_date=$(git -C gn-src log -1 --format=%cs)" >> $GITHUB_OUTPUT
          echo "short_ver=$(git -C gn-src rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
          echo "long_ver=$(git -C gn-src rev-parse HEAD | head -c 12)" >> $GITHUB_OUTPUT
          echo "commit_position=$(git -C gn-src rev-list --count HEAD)" >> $GITHUB_OUTPUT
          git -C gn-src archive --output=gn.tar.gz HEAD
          echo "checksum=$(sha256sum gn-src/gn.tar.gz | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

  update:
    needs:
      - get_current_info
      - get_latest_info
    if: needs.get_current_info.outputs.pkg_source_version != needs.get_latest_info.outputs.commit_sha
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Makefile
        run: |
          sed -i "s/PKG_SOURCE_DATE:=.*/PKG_SOURCE_DATE:=${{ needs.get_latest_info.outputs.commit_date }}/" gn/Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=${{ needs.get_latest_info.outputs.commit_sha }}/" gn/Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.get_latest_info.outputs.checksum }}/" gn/Makefile

      - name: Update last_commit_position.h
        run: |
          COMMIT_POSITION_FILE="gn/src/out/last_commit_position.h"
          if [ -f "$COMMIT_POSITION_FILE" ]; then
            sed -i "6s/#define LAST_COMMIT_POSITION_NUM .*/#define LAST_COMMIT_POSITION_NUM ${{ needs.get_latest_info.outputs.commit_position }}/" "$COMMIT_POSITION_FILE"
            sed -i "7s/#define LAST_COMMIT_POSITION .*/#define LAST_COMMIT_POSITION \"${{ needs.get_latest_info.outputs.commit_position }} (${{ needs.get_latest_info.outputs.long_ver }})\"/" "$COMMIT_POSITION_FILE"
          fi

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gn/Makefile gn/src/out/last_commit_position.h
          git diff --cached --quiet && { echo "No changes"; exit 0; }
          git commit -m "gn: auto update to ${{ needs.get_latest_info.outputs.short_ver }}"
          git push origin main
