name: "shadowsocks-rust"
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: "0 */8 * * *"
env:
  TZ: Asia/Shanghai

jobs:
  job_init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run: |
          sudo timedatectl set-timezone "$TZ"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
        
      - name: SSH connection to Actions
        uses: kenzok78/ssh-action@master
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')    

  # 串行执行所有shadowsocks-rust架构，避免同时修改同一个Makefile
  job_auto_update_shadowsocks_rust:
    if: ${{ always() }}
    needs: job_init
    runs-on: ubuntu-latest
    name: update-shadowsocks-rust-all-arch
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run: |
          cd && mkdir -p pack && cd pack
          sudo timedatectl set-timezone "$TZ"

      - name: Check version and update all architectures
        run: |
          cd $GITHUB_WORKSPACE/shadowsocks-rust
          
          # 检查版本 - 增加错误处理和调试信息
          Old_PKG_VERSION=$(sed -n '/^PKG_VERSION:=/p' Makefile | awk -F '=' '{print $2}')
          
          echo "获取shadowsocks-rust最新版本..."
          
          # 首先检查API响应
          api_response=$(curl -sL "https://api.github.com/repos/shadowsocks/shadowsocks-rust/releases")
          echo "API响应前200字符: $(echo "$api_response" | head -c 200)"
          
          # 检查是否是有效的JSON
          if ! echo "$api_response" | jq . >/dev/null 2>&1; then
            echo "❌ API返回的不是有效的JSON格式"
            echo "完整响应: $api_response"
            exit 1
          fi
          
          # 检查是否是数组
          if ! echo "$api_response" | jq 'type' | grep -q "array"; then
            echo "❌ API返回的不是数组格式"
            echo "返回类型: $(echo "$api_response" | jq 'type')"
            exit 1
          fi
          
          # 获取最新版本，增加更多调试信息
          New_PKG_VERSION=$(echo "$api_response" | jq -r '
            if type == "array" and length > 0 then
              map(select(has("prerelease") and .prerelease == false)) |
              if length > 0 then
                .[0].tag_name | sub("^v"; "")
              else
                error("没有找到非预发布版本")
              end
            else
              error("API返回空数组或非数组")
            end
          ')
          
          # 检查jq命令是否成功
          if [ $? -ne 0 ] || [ -z "$New_PKG_VERSION" ]; then
            echo "❌ 无法解析版本信息，尝试备用方法..."
            # 备用方法：获取第一个release的tag_name
            New_PKG_VERSION=$(echo "$api_response" | jq -r '.[0].tag_name // empty' | sed 's/^v//')
            
            if [ -z "$New_PKG_VERSION" ]; then
              echo "❌ 备用方法也失败了，退出"
              exit 1
            fi
            echo "✅ 使用备用方法获取到版本: $New_PKG_VERSION"
          fi
          
          echo "shadowsocks-rust当前版本: $Old_PKG_VERSION"
          echo "shadowsocks-rust最新版本: $New_PKG_VERSION"
          
          if [ "$Old_PKG_VERSION" != "$New_PKG_VERSION" ]; then
            echo "检测到新版本，开始更新所有架构..."
            
            # 更新版本号
            sed -i "/^PKG_VERSION:=/c PKG_VERSION:=$New_PKG_VERSION" Makefile
            echo "SHADOWSOCKS_UPDATED=true" >> $GITHUB_ENV
            echo "SHADOWSOCKS_VERSION=$New_PKG_VERSION" >> $GITHUB_ENV
            
            # 创建下载目录
            cd ~/pack && mkdir -p shadowsocks-rust && cd shadowsocks-rust
            
            # 定义架构信息：行号、缩进、下载URL、文件名
            declare -A arch_info=(
              # 格式: "hash_line:indent:repo_owner:filename"
              [24]="2:shadowsocks:shadowsocks-v$New_PKG_VERSION.aarch64-unknown-linux-musl.tar.xz"
              [30]="4:shadowsocks:shadowsocks-v$New_PKG_VERSION.arm-unknown-linux-musleabi.tar.xz"
              [33]="4:shadowsocks:shadowsocks-v$New_PKG_VERSION.arm-unknown-linux-musleabihf.tar.xz"
              [37]="2:shadowsocks:shadowsocks-v$New_PKG_VERSION.i686-unknown-linux-musl.tar.xz"
              [40]="2:shadowsocks:shadowsocks-v$New_PKG_VERSION.x86_64-unknown-linux-musl.tar.xz"
              [43]="2:sbwml:shadowsocks-v$New_PKG_VERSION.mips-unknown-linux-musl.tar.xz"
              [46]="2:sbwml:shadowsocks-v$New_PKG_VERSION.mipsel-unknown-linux-musl.tar.xz"
            )
            
            # 处理每个架构
            for hash_line in "${!arch_info[@]}"; do
              info="${arch_info[$hash_line]}"
              IFS=':' read -r indent repo_owner filename <<< "$info"
              
              echo "处理架构文件: $filename (行号: $hash_line, 缩进: ${indent}空格)"
              
              # 构建下载URL
              if [ "$repo_owner" = "shadowsocks" ]; then
                download_url="https://github.com/shadowsocks/shadowsocks-rust/releases/download/v${New_PKG_VERSION}/${filename}"
              elif [ "$repo_owner" = "sbwml" ]; then
                download_url="https://github.com/sbwml/shadowsocks-rust-mips/releases/download/v${New_PKG_VERSION}/${filename}"
              fi
              
              echo "下载URL: $download_url"
              
              # 下载文件，增加重试机制
              download_success=false
              for attempt in 1 2 3; do
                echo "尝试下载 $filename (第${attempt}次)"
                if wget -q "$download_url"; then
                  download_success=true
                  break
                else
                  echo "下载失败，等待5秒后重试..."
                  sleep 5
                fi
              done
              
              if [ "$download_success" = true ] && [ -f "$filename" ]; then
                # 计算哈希
                PKG_HASH=$(sha256sum "$filename" | awk '{print $1}')
                echo "$filename 哈希值: $PKG_HASH"
                
                # 根据缩进格式更新哈希
                cd $GITHUB_WORKSPACE/shadowsocks-rust
                if [ "$indent" = "2" ]; then
                  sed -i "${hash_line}c\  PKG_HASH:=$PKG_HASH" Makefile
                elif [ "$indent" = "4" ]; then
                  sed -i "${hash_line}c\    PKG_HASH:=$PKG_HASH" Makefile
                fi
                
                cd ~/pack/shadowsocks-rust
              else
                echo "❌ 警告: 无法下载文件 $filename，跳过此架构"
                # 可以选择继续处理其他架构，或者退出
                # exit 1  # 如果希望任何一个文件下载失败就退出，取消注释这行
              fi
            done
            
            echo "所有架构文件哈希更新完成"
          else
            echo "shadowsocks-rust版本为最新版本,无需更新"
            echo "SHADOWSOCKS_UPDATED=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push shadowsocks-rust Changes
        if: env.SHADOWSOCKS_UPDATED == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          
          # 配置git
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # 检查是否有变更
          if [ -n "$(git status --porcelain)" ]; then
            echo "检测到shadowsocks-rust文件变更，准备提交..."
            git add shadowsocks-rust/Makefile
            git commit -m "shadowsocks-rust: update to $SHADOWSOCKS_VERSION"
            git push origin main
            echo "✅ 已成功提交并推送 shadowsocks-rust 更改到版本 $SHADOWSOCKS_VERSION"
          else
            echo "没有检测到shadowsocks-rust文件变更"
          fi
