name: "shadow-tls"
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: "0 */8 * * *"
env:
  TZ: Asia/Shanghai

jobs:
  job_init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run: |
          sudo timedatectl set-timezone "$TZ"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
        
      - name: SSH connection to Actions
        uses: kenzok78/ssh-action@master
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

  # 串行执行所有shadow-tls架构，避免同时修改同一个Makefile
  job_auto_update_shadow_tls:
    if: ${{ always() }}
    needs: job_init
    runs-on: ubuntu-latest
    name: update-shadow-tls-all-arch
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run: |
          cd && mkdir -p pack && cd pack
          sudo timedatectl set-timezone "$TZ"

      - name: Check version and update all architectures
        run: |
          cd $GITHUB_WORKSPACE/shadow-tls
          
          # 检查版本
          Old_PKG_VERSION=$(sed -n '/^PKG_VERSION:=/p' Makefile | awk -F '=' '{print $2}')
          New_PKG_VERSION=$(curl -sL "https://api.github.com/repos/ihciah/shadow-tls/releases" | jq -r 'map(select(.prerelease|not)) | first | .tag_name' | sed -e 's/.*v//')
          
          echo "shadow-tls当前版本: $Old_PKG_VERSION"
          echo "shadow-tls最新版本: $New_PKG_VERSION"
          
          if [ "$Old_PKG_VERSION" != "$New_PKG_VERSION" ]; then
            echo "检测到新版本，开始更新所有架构..."
            
            # 更新版本号
            sed -i "/^PKG_VERSION:=/c PKG_VERSION:=$New_PKG_VERSION" Makefile
            echo "SHADOW_TLS_UPDATED=true" >> $GITHUB_ENV
            echo "SHADOW_TLS_VERSION=$New_PKG_VERSION" >> $GITHUB_ENV
            
            # 创建下载目录
            cd ~/pack && mkdir -p shadow-tls && cd shadow-tls
            
            # 定义所有架构和对应的哈希行及文件名
            declare -A arch_files=(
              [14]="shadow-tls-aarch64-unknown-linux-musl"
              [18]="shadow-tls-armv7-unknown-linux-musleabihf"
              [21]="shadow-tls-armv7-unknown-linux-musleabihf"
              [24]="shadow-tls-arm-unknown-linux-musleabi"
              [28]="shadow-tls-x86_64-unknown-linux-musl"
            )
            
            # 定义缩进格式
            declare -A indent_spaces=(
              [14]=4  # aarch64: 4空格
              [18]=8  # armv7-musleabihf: 8空格
              [21]=8  # armv7-musleabihf (重复): 8空格
              [24]=8  # arm-musleabi: 8空格
              [28]=4  # x86_64: 4空格
            )
            
            # 下载所有文件并计算哈希
            for hash_line in "${!arch_files[@]}"; do
              file_name="${arch_files[$hash_line]}"
              spaces="${indent_spaces[$hash_line]}"
              echo "处理架构文件: $file_name (行号: $hash_line, 缩进: ${spaces}空格)"
              
              # 下载文件
              wget -q "https://github.com/ihciah/shadow-tls/releases/download/v$New_PKG_VERSION/$file_name"
              
              if [ -f "$file_name" ]; then
                # 计算哈希
                PKG_HASH=$(sha256sum "$file_name" | awk '{print $1}')
                echo "$file_name 哈希值: $PKG_HASH"
                
                # 根据缩进格式更新哈希
                cd $GITHUB_WORKSPACE/shadow-tls
                if [ "$spaces" = "4" ]; then
                  sed -i "${hash_line}c\    PKG_HASH:=$PKG_HASH" Makefile
                elif [ "$spaces" = "8" ]; then
                  sed -i "${hash_line}c\        PKG_HASH:=$PKG_HASH" Makefile
                fi
                
                cd ~/pack/shadow-tls
              else
                echo "警告: 无法下载文件 $file_name"
              fi
            done
            
            echo "所有架构文件哈希更新完成"
          else
            echo "shadow-tls版本为最新版本,无需更新"
            echo "SHADOW_TLS_UPDATED=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push shadow-tls Changes
        if: env.SHADOW_TLS_UPDATED == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          
          # 配置git
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # 检查是否有变更
          if [ -n "$(git status --porcelain)" ]; then
            echo "检测到shadow-tls文件变更，准备提交..."
            git add shadow-tls/Makefile
            git commit -m "shadow-tls: update to $SHADOW_TLS_VERSION"
            git push origin main
            echo "✅ 已成功提交并推送 shadow-tls 更改到版本 $SHADOW_TLS_VERSION"
          else
            echo "没有检测到shadow-tls文件变更"
          fi
